### ISSUE TITLE
gpu checking and template

### ISSUE THREAD

**Issue by martinmalek** [SoMoney/ansible-ollama#1]
Hi,

Thanks for this. 

I noticed that the gpu check was failing for me. I assume because of grep returning 0 on match only.

I changed it to not failing on 1 

```
- name: "Check if system has NVIDIA GPU using lspci"
  shell: "lspci | grep -i nvidia"
  register: nvidia_gpu_check
  when: ansible_distribution == 'Ubuntu'
  failed_when: nvidia_gpu_check.rc not in [ 0, 1 ]
```

Additionally the docker-compose.j2 needs a check for gpu is it will fail when there is no driver.

```
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
{% if nvidia_gpu_check.rc == 0 %}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
{% endif %}
    networks:
      - ollama_network

  open-webui:
    image: ghcr.io/open-webui/open-webui:cuda
    container_name: open-webui
    restart: always
    volumes:
      - open_webui_data:/app/backend/data
    ports:
      - "3000:8080"
    depends_on:
      - ollama
{% if nvidia_gpu_check.rc == 0 %}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
{% endif %}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ollama_network
```
